### ISSUE TITLE
Issue with shiboken2

### ISSUE THREAD

**Issue by giumas** [conda-forge/pyside2-feedstock#10]
I am attempting to use this Conda package to wrap a custom Qt5 widget, and I am having troubles: https://stackoverflow.com/questions/47607616/shiboken2-and-custom-qt-widget

My issue is most likely unrelated to the Conda package in itself, but any thought on it? Anybody is successfully using it for binding?

**Comment by jschueller** [comment]
Ask upstream

**Comment by giumas** [comment]
Sure! I have already asked. I was just wondering if you are using `shiboken2` in any project.
