### ISSUE TITLE
Tracking issue for upstream bug reports

### ISSUE THREAD

**Issue by hmaarrfk** [conda-forge/pyside2-feedstock#133]
### Comment:

- [ ] [PYSIDE-2057 shiboken2 stores compiler value at compile time](https://bugreports.qt.io/browse/PYSIDE-2057)
- [ ] [PYSIDE-802 Enable PySide/Shiboken cross compilation for different targets](https://bugreports.qt.io/browse/PYSIDE-802)

**Comment by jschueller** [comment]
its more up to date in the meta.yaml, lets use that for ref
