### ISSUE TITLE
version 2.0.0~alpha0 is not a valid conda version

### ISSUE THREAD

**Issue by kalefranz** [conda-forge/pyside2-feedstock#14]
I'm not sure how this package got released, but it's sorta breaking the world for a lot of conda-forge users right now.

https://anaconda.org/conda-forge/pyside2/files?version=2.0.0~alpha0&page=1

**Comment by fredrikaverpil** [comment]
@kalefranz I realize this isn't a solution but I just want to mention these wheels in case you're having trouble:

- https://github.com/fredrikaverpil/pyside2-windows
- https://github.com/fredrikaverpil/pyside2-macos
- https://github.com/fredrikaverpil/pyside2-linux

**Comment by jschueller** [comment]
@conda-forge/core could you remove the 2.0.0~alpha0 packages on anaconda.org ?

**Comment by mbargull** [comment]
@isuruf already moved them to the `broken` label.

**Comment by jschueller** [comment]
How is it not a valid version ?  seems conda build was happy.

**Comment by jschueller** [comment]
Thanks @isuruf

**Comment by mbargull** [comment]
> How is it not a valid version ? seems conda build was happy.

I guess, we'll have to add checks for this to `conda-build`, some more handling (I suppose ignoring) of invalid package data in `conda`, and maybe also something else (bot command or something?) for `conda-forge` that makes a second step -- apart from opening a branch -- necessary before builds are issued.

**Comment by kalefranz** [comment]
Discussion of how conda interprets and handles versions is in https://github.com/conda/conda/issues/2071

**Comment by kalefranz** [comment]
Also, for reference, I just created https://github.com/conda/conda-build/issues/2670
