### ISSUE TITLE
How to get QtWebEngineWidgets on PySide6?

### ISSUE THREAD

**Issue by fabioz** [conda-forge/pyside2-feedstock#167]
### Comment:

I'm getting an `ImportError` with the code:

`from PySide6 import QtWebEngineWidgets`

with `PySide6` from `conda-forge` (I tested with `6.4.0` as well as `6.4.1`).

Note: It seems to be available in `PySide6, version 6.4.1` from `pypi`.

**Comment by fabioz** [comment]
Humm... how about an approach where the additional modules are built in a separate package?

I believe this is what's done in https://anaconda.org/conda-forge/pyqtwebengine...

**Comment by hmaarrfk** [comment]
The fundamental problems is that the underlying c library doesn't exist for pyside6. We weren't able to compile it.
