### ISSUE TITLE
pyside6-uic command

### ISSUE THREAD

**Issue by JaRoSchm** [conda-forge/pyside2-feedstock#193]
### Comment:

Hi, in https://github.com/spyder-ide/qtpy/pull/440 we see that if PySide6 6.4.3 is installed from conda-forge the pyside6-uic command is not available under Linux and macOS. Is this something which could be added?

**Comment by jschueller** [comment]
indeed, I only added it in 6.5.x, can you upgrade ?

**Comment by JaRoSchm** [comment]
Ah, thank you for the info!
