### ISSUE TITLE
UnsatisfiableError with Python 3.6 x64 on Windows 

### ISSUE THREAD

**Issue by giumas** [conda-forge/pyside2-feedstock#2]
With the environment described in the subject, I have attempted to run:

`conda install -c conda-forge pyside2`

but I got:

```
UnsatisfiableError: The following specifications were found to be in conflict:
  - pyside
  - pyside2
  - python 3.6*
Use "conda info <package>" to see the dependencies for each package.
```

Any hint of what is going on? Why `pyside` is listed?

**Comment by jschueller** [comment]
on what platform ?

**Comment by giumas** [comment]
Win 10

**Comment by jschueller** [comment]
it seems pyside and pyside2 are not coinstallable because of qt 4 and 5 are not coinstallable, please try remove pyside first

**Comment by giumas** [comment]
I created a clean env and it worked! You may want to add a note about this incompatibility.
