### ISSUE TITLE
python3.7 support

### ISSUE THREAD

**Issue by looooo** [conda-forge/pyside2-feedstock#21]
Are there any show-stoppers for python3.7?

**Comment by jschueller** [comment]
I  believe it just needs some rerendering.

**Comment by looooo** [comment]
I tried it, but no 3.7 stuff was added.

**Comment by jschueller** [comment]
Indeed, I heard it was coming soon, lets wait a bit more.

**Comment by jschueller** [comment]
seems to go fine except one test:

https://circleci.com/gh/conda-forge/pyside2-feedstock/129?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

maybe related to https://codereview.qt-project.org/#/c/234124/ that would need backporting

**Comment by looooo** [comment]
how did you update the recipe to build with python3.7?

**Comment by jschueller** [comment]
I edited manually my ~/miniconda/conda_build_config.yaml
