### ISSUE TITLE
PY_LIMITED_API is forced for packages depending on shiboken

### ISSUE THREAD

**Issue by looooo** [conda-forge/pyside2-feedstock#232]
### Comment:

FreeCAD is not restricted to the PY_LIMITED_API but Shiboken somhow restricts FreeCAD to use the PY_LIMITED_API. It would be nice if PY_LIMITED_API is not propagated.

**Comment by jschueller** [comment]
hellooooo can you retry after #241 if that works for you ?

**Comment by looooo** [comment]
thanks, yes I can confirm that this is not an issue anymore. Thanks for your work!!! FreeCAD packaged for conda-forge would not be possible with the amazing work you are doing with packaging qt and pyside2.
