### ISSUE TITLE
Remove clang constraint

### ISSUE THREAD

**Issue by h-vetinari** [conda-forge/pyside2-feedstock#235]
Now that the upstream fix for https://bugreports.qt.io/browse/PYSIDE-2288 has landed in 6.5.1 (and apparently some 5.15.x), we should revert https://github.com/conda-forge/pyside2-feedstock/commit/c5f64483fe83066ccbae2b03218e27ba7bc9a59c. There's some related commits mentioned in the issue, and some can be [found](https://github.com/search?q=repo%3Apyside%2Fpyside-setup+PYSIDE-2288&type=commits) on the repo

Sister-issue to https://github.com/conda-forge/qt-main-feedstock/issues/285

**Comment by hmaarrfk** [comment]
where do you see that the 5.15.X has landed?

I think we already released it or the 6.x branch:
https://github.com/conda-forge/pyside2-feedstock/blob/pyside6/recipe/meta.yaml

**Comment by h-vetinari** [comment]
> where do you see that the 5.15.X has landed?

Based on the below, but I haven't been able (also for the commits in 6.5) to find the hashes mentioned in the issue in the repo itself.

![image](https://github.com/user-attachments/assets/246b5613-b702-40ad-88b6-bdc4dff03365)

**Comment by hmaarrfk** [comment]
i think this was resolved with the release of 5.15.15
