### ISSUE TITLE
Marking PySide 6.8.0 as broken???

### ISSUE THREAD

**Issue by hmaarrfk** [conda-forge/pyside2-feedstock#247]
### Comment:

I mean this bug is pretty disastrous 
https://github.com/spyder-ide/qtpy/issues/494

**Comment by ccordoba12** [comment]
I think that's a good idea, especially because Matplotlib depends now on PySide 6 (which I still think is a bad idea, by the way, given how buggy PySide is).

**Comment by hmaarrfk** [comment]
See fix https://github.com/conda-forge/pyside2-feedstock/pull/249 I tried to add a few checks to ensure this disaster doesn't happen again.
