### ISSUE TITLE
conda-forge doesn't use CDT

### ISSUE THREAD

**Issue by hmaarrfk** [conda-forge/pyside2-feedstock#25]
https://github.com/conda-forge/pyside2-feedstock/blob/942844433e95d6c537d093753f5e5d3bb150b316/recipe/meta.yaml#L23

I'm pretty sure that conda-forge doesn't use CDTs

There were a few discussion points about that but generally, that is where conda-forge and defaults diverge.

**Comment by jschueller** [comment]
I think its necessary for qt packages and its dependencies, see qt, qwt recipes for example.

**Comment by hmaarrfk** [comment]
Thanks for the explanation. 

I guess it is necessary for graphics stuff..

maybe we can minimize their use a little bit?
There seems to be some x11 packages that we can probably include in build.

oh well.

**Comment by jschueller** [comment]
we cant, as we have to link with libgl that lies in /usr/lib64, but avoid system libs (zlibs etc), we need something that isolates libgl and its dependent libs
