### ISSUE TITLE
Update to 5.11

### ISSUE THREAD

**Issue by FSund** [conda-forge/pyside2-feedstock#27]
Version 5.11.3 fixes a memory leak in QImage, so it would be nice if the conda-forge version was updated to 5.11.3 or beyond.

EDIT: Sorry, forgot the link to the bug report/fix: https://bugreports.qt.io/browse/PYSIDE-140

**Comment by jschueller** [comment]
I backported it: https://github.com/conda-forge/pyside2-feedstock/pull/28

**Comment by nehaljwani** [comment]
I have pyside 5.12.3 builds at https://anaconda.org/nehaljwani/pyside2 , if anyone is interested. Works on CentOS6

**Comment by jschueller** [comment]
Interesting.
Does Qt3D work ?
I recently reported https://bugreports.qt.io/projects/PYSIDE/issues/PYSIDE-1026

**Comment by jschueller** [comment]
@nehaljwani it's 5.12.4 here now!
