### ISSUE TITLE
pyside2 5.12.1 win: wrong SHIBOKEN_SHARED_LIBRARY_DIR

### ISSUE THREAD

**Issue by looooo** [conda-forge/pyside2-feedstock#43]
in /Library/lib/cmake/Shiboken2-5.13.1/Shiboken2Config.cp37-win_amd64.cmake
```
set_and_check(SHIBOKEN_SHARED_LIBRARY_DIR "${PACKAGE_PREFIX_DIR}/bin")
```

should be:
```
set_and_check(SHIBOKEN_SHARED_LIBRARY_DIR "${PACKAGE_PREFIX_DIR}/Library/lib")
```

Edit: we are now using library dir via imported target properties.: https://github.com/FreeCAD/FreeCAD/blob/master/cMake/FreeCAD_Helpers/SetupShibokenAndPyside.cmake#L49

**Comment by looooo** [comment]
btw.: the configuration file doesn't look very good:
```
#----------------------------------------------------------------
# Generated CMake target import file for configuration "Release".
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

# Import target "Shiboken2::libshiboken" for configuration "Release"
set_property(TARGET Shiboken2::libshiboken APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(Shiboken2::libshiboken PROPERTIES
  IMPORTED_IMPLIB_RELEASE "D:/bld/pyside2_1569322331212/_h_env/Library/lib/shiboken2.cp37-win_amd64.lib"
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/bin/shiboken2.cp37-win_amd64.dll"
  )

list(APPEND _IMPORT_CHECK_TARGETS Shiboken2::libshiboken )
list(APPEND _IMPORT_CHECK_FILES_FOR_Shiboken2::libshiboken "D:/bld/pyside2_1569322331212/_h_env/Library/lib/shiboken2.cp37-win_amd64.lib" "${_IMPORT_PREFIX}/bin/shiboken2.cp37-win_amd64.dll" )

# Import target "Shiboken2::shiboken2" for configuration "Release"
set_property(TARGET Shiboken2::shiboken2 APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(Shiboken2::shiboken2 PROPERTIES
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/bin/shiboken2.exe"
  )

list(APPEND _IMPORT_CHECK_TARGETS Shiboken2::shiboken2 )
list(APPEND _IMPORT_CHECK_FILES_FOR_Shiboken2::shiboken2 "${_IMPORT_PREFIX}/bin/shiboken2.exe" )

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
```

**Comment by jschueller** [comment]
looks like an upstream issue, please open an issue on their jira

**Comment by jschueller** [comment]
@looooo I think there is no bug ihmo SHIBOKEN_SHARED_LIBRARY_DIR is intended to contain the path to runtime library (.so/.dylib/.dll); see pyside2/tests/CMakeLists.txt:12:        ```set(TEST_LIBRARY_PATH   "${libpyside_BINARY_DIR};${pysidetest_BINARY_DIR};${SHIBOKEN_SHARED_LIBRARY_DIR};$ENV{PATH}")```
and on windows the runtime library .dll is indeed located in prefix/bin

**Comment by looooo** [comment]
Ah I see, so the real problem is linking to the runtime-library. This is the output if I try to do so:
```
[2340/3244] Linking CXX shared library bin\FreeCADGui.dll
.....
%PREFIX%\Library\bin\shiboken2.cp37-win_amd64.dll : fatal error LNK1107: invalid or corrupt file: cannot read at 0x348
```

**Comment by jschueller** [comment]
Try to lin to the one of the provided targets Shiboken2::shiboken2 or Shiboken2::libshiboken

**Comment by looooo** [comment]
I think we are already doing so:
https://github.com/FreeCAD/FreeCAD/blob/3939e4543ef4be6c50581d9bff77e930fb1d9d03/cMake/FreeCAD_Helpers/SetupShibokenAndPyside.cmake#L49

`get_property(SHIBOKEN_LIBRARY TARGET Shiboken2::libshiboken PROPERTY IMPORTED_LOCATION_RELEASE)`

It works on linux and osx but results in the error reported above for win: https://github.com/conda-forge/pyside2-feedstock/issues/43#issuecomment-541759200

**Comment by jschueller** [comment]
you want IMPORTED_IMPLIB instead of IMPORTED_LOCATION
but its simpler not to use the location, just link directly to Shiboken2::libshiboken

**Comment by looooo** [comment]
thx, I will check in the next iteration.

**Comment by looooo** [comment]
hmm, didn't work out of the box. I now see undefined references to shiboken funtions (windows, linux). Osx seems to work with your suggestion. Does it make any sense to use IMPORTED_IMPLIB_RELEASE insead of IMPORTED_IMPLIB?

**Comment by looooo** [comment]
thanks. Using the imported target indeed works.
