### ISSUE TITLE
python3.8 needs to be patched

### ISSUE THREAD

**Issue by looooo** [conda-forge/pyside2-feedstock#56]
regarding: https://bugreports.qt.io/browse/PYSIDE-939
py3.8 needs to be patched.

for example, the issues occur here:
https://github.com/conda-forge/freecad-feedstock/pull/30

**Comment by jschueller** [comment]
I dont understand what need to be patched : the issue is mentionning a cpython commit that occured before the release, did it not get into the release ? otherwise pyside2 has no pending patch regarding that issue.

**Comment by looooo** [comment]
I guess there is nothing to do for pyside2. But for the py3.8 migration to continue we need to wait for a patched python3.8 if I understood it correctly.

**Comment by hmaarrfk** [comment]
also: https://bugreports.qt.io/browse/PYSIDE-1140

**Comment by hmaarrfk** [comment]
https://codereview.qt-project.org/c/pyside/pyside-setup/+/282705

**Comment by looooo** [comment]
@hmaarrfk should we wait for a new version or should we patch the current version?

**Comment by hmaarrfk** [comment]
I tried to patch it quickly on linux, it didn't fully pass. I figure we should just wait.

**Comment by hmaarrfk** [comment]
asking for a backport might be an option.

**Comment by looooo** [comment]
Regarding pyside2-gitter, we need to wait for python3.8.1 and once available have to build the 5.14 version of pyside2 to make pyside2 available for python3.8.

ref.: https://github.com/conda-forge/python-feedstock/issues/293

**Comment by looooo** [comment]
As pside 5.14 seems to be not compatible with qt5.12 we need to backport the py3.8 fixes which were added to version 5.14.

**Comment by hmaarrfk** [comment]
Wanna try to go through the patching exercise. At least 2 patches seem necessary.

Maybe custom patching too

**Comment by looooo** [comment]
I tried to backport the necessary py3.8 commits and it seems this worked (at least for linux). If you want to test, I uploaded a package to channel freecad/label/testing.

https://github.com/conda-forge/pyside2-feedstock/pull/62
