### ISSUE TITLE
ImportError on Windows 10 x64

### ISSUE THREAD

**Issue by jeremyherbert** [conda-forge/pyside2-feedstock#58]
Installing pyside2 from conda-forge on windows 10 x64 doesn't work properly.

```
(base) C:\Users\jeremy>python -c "from PySide2 import QtCore"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: DLL load failed: The specified module could not be found.
```

Installed packages are here: https://gist.github.com/jeremyherbert/d6ec7f2624b038289db0f16002428c92

This is likely due to DLL version mismatch. Qt is version `5.9.7` while pyside2 is version `5.9.0a1`. Given that anaconda ships with this version of Qt, there should probably be a version of pyside2 which matches this.

To reproduce:
1. Clean install of Anaconda 2019.10 with python 3.7 on Windows 10 x64
2. `conda install -c conda-forge pyside2` (note that dependency solver fails on the first pass!)
3. `python -c "from PySide2 import QtCore"`

Workaround is to install everything from conda-forge in a new environment: `conda create -n testenvqt -c conda-forge python=3.7 pyside2=5.12.4`

`conda list` of the working environment is here: https://gist.github.com/jeremyherbert/a57d667b3162f9e2e85d4e3f53675e2b

**Comment by jschueller** [comment]
yes, you have to install everything from conda-forge, mixing packages from defaults is not supported
