### ISSUE TITLE
Using PySide2 5.14 instead of 5.13

### ISSUE THREAD

**Issue by cmaureir** [conda-forge/pyside2-feedstock#70]
Not really an issue, but I wanted to get in touch with the maintainers of the conda recipe.

I know moving forward with Qt versions is a major problem due to all the dependencies that updating Qt might break, but in any case, many things are fixed or improved with the new PySide2 versions, including the compatibility with **Python 3.8**, `qApp` macro issues, the `__signature__` story, etc.

For this, we decided to make **PySide2 5.14 compatible with Qt 5.13 (and 5.12)**, in the sense that one can build it against that version on Qt, having then all the improvements to `libshiboken/libpyside`.

I don't know if this can cause any issues on the applications depending on PySide2, but the only source incompatibility now is that when working with `qApp` one cannot delete it implicitly, but needs to call the `shutdown()` method.

Maybe this will help the situation you are currently facing with all the additional patches you need to apply for the recipe.

We are following the conda support story, so in case of further issues, don't hesitate to drop us a report in [JIRA](https://bugreports.qt.io/projects/PYSIDE/).

**Comment by looooo** [comment]
If there is not too much work involved I think we should update:
https://github.com/conda-forge/pyside2-feedstock/pull/71

**Comment by jschueller** [comment]
we cant do that, because the uic utils are part on qt now instead of pyside; so moving to pyside 5.14 would mean no more uic utils

**Comment by looooo** [comment]
ok, so I guess we should wait for qt5.15?

**Comment by jschueller** [comment]
yes

**Comment by cmaureir** [comment]
@jschueller please ping me here or any other [platform](https://wiki.qt.io/Qt_for_Python#Community) in case you face some issues while building or runtime bugs, hopefully 5.15 can be working without any problem :smile: :snake:

**Comment by jschueller** [comment]
see https://github.com/conda-forge/qt-feedstock/pull/156, I already tried to update to 5.15 and its not going to be easy
