### ISSUE TITLE
pyi files are missing on OSX, making mypy typechecking impossible

### ISSUE THREAD

**Issue by rggjan** [conda-forge/pyside2-feedstock#89]
See https://github.com/conda-forge/pyside2-feedstock/issues/53 which is closed but [doesn't seem to be fixed](https://github.com/conda-forge/pyside2-feedstock/issues/53#issuecomment-867502457)...

**Comment by hmaarrfk** [comment]
Maybe the patch broke. Help fixing it would be appreciated.

Can you maybe help us create a command that would fail without the type hints? that would help us add it to the CI so that we can ensure it gets fixed more permanently.

Also I realize this is 1 year later, so maybe things are fixed now.
